---------------------------------------------------
-- BUSCANDO O SEGUNDO REGISTRO x Cliente

SELECT 
	A1_COD, A1_LOJA, A1_NOME ,
	PENULTIMA = (
				SELECT TOP 1
					MAX(F2_EMISSAO) AS EMISSAO 
				FROM
					SF2010
				WHERE 
					F2_CLIENTE = A1_COD AND F2_LOJA = A1_LOJA AND F2_EMISSAO >'20190901'
					--AQUI ESTA A FÓRMULA, REPETINDO A QUERY E BUSCANDO O F2_EMISSAO < QUE O MAX:
					AND F2_EMISSAO < (SELECT  MAX(F2_EMISSAO) AS EMISSAO  FROM SF2010 WHERE F2_CLIENTE = A1_COD AND F2_LOJA = A1_LOJA AND F2_EMISSAO >'20190901' AND D_E_L_E_T_ <>'*' GROUP BY F2_CLIENTE, F2_LOJA)
					AND D_E_L_E_T_ <>'*'
				GROUP BY 
					F2_CLIENTE,F2_LOJA, F2_EMISSAO
				ORDER BY 
					F2_EMISSAO DESC
				)
FROM 
	SA1010 (NOLOCK)
WHERE 
	A1_COD IN ('000001','000002') 
	AND A1_LOJA = ('01')


---
@Thiago.Andrrade
