-- No Exemplo abaixo, vamos obter o Retorno do CASE através de um SELECT

SELECT
	D2_DOC AS NOTA,
	D2_CLIENTE AS CLI_FORN,
	CASE
		WHEN D2_TIPO IN ('D','B') THEN (SELECT A2_CGC FROM SA2010 WHERE A2_COD = D2_CLIENTE AND A2_LOJA = D2_LOJA AND D_E_L_E_T_ ='')
		WHEN D2_TIPO NOT IN ('D','B') THEN (SELECT A1_CGC FROM SA1010 WHERE A1_COD = D2_CLIENTE AND A1_LOJA = D2_LOJA AND D_E_L_E_T_ ='')
	END AS CNPJ
FROM
	SD2010 (NOLOCK)
WHERE
	D2_EMISSAO >'20190715'
	AND D_E_L_E_T_ =''
ORDER BY 
	D2_DOC
  
 ---
 @thiago.andrrade
