-- SUM e CASE agrupando o Resultado de cada Mês em uma Coluna
SELECT 
	D2_CLIENTE, D2_LOJA,
	SUM(CASE WHEN MONTH(D2_EMISSAO) = '01' THEN D2_TOTAL ELSE 0 END) AS JAN_FAT,
	SUM(CASE WHEN MONTH(D2_EMISSAO) = '02' THEN D2_TOTAL ELSE 0 END) AS FEV_FAT,
	SUM(CASE WHEN MONTH(D2_EMISSAO) = '03' THEN D2_TOTAL ELSE 0 END) AS MAR_FAT,
	SUM(CASE WHEN MONTH(D2_EMISSAO) = '04' THEN D2_TOTAL ELSE 0 END) AS ABR_FAT,
	SUM(CASE WHEN MONTH(D2_EMISSAO) = '05' THEN D2_TOTAL ELSE 0 END) AS MAI_FAT,
	SUM(CASE WHEN MONTH(D2_EMISSAO) = '06' THEN D2_TOTAL ELSE 0 END) AS JUN_FAT,
	SUM(CASE WHEN MONTH(D2_EMISSAO) = '07' THEN D2_TOTAL ELSE 0 END) AS JUL_FAT,
	SUM(CASE WHEN MONTH(D2_EMISSAO) = '08' THEN D2_TOTAL ELSE 0 END) AS AGO_FAT,
	SUM(CASE WHEN MONTH(D2_EMISSAO) = '09' THEN D2_TOTAL ELSE 0 END) AS SET_FAT,
	SUM(CASE WHEN MONTH(D2_EMISSAO) = '10' THEN D2_TOTAL ELSE 0 END) AS OUT_FAT,
	SUM(CASE WHEN MONTH(D2_EMISSAO) = '11' THEN D2_TOTAL ELSE 0 END) AS NOV_FAT,
	SUM(CASE WHEN MONTH(D2_EMISSAO) = '12' THEN D2_TOTAL ELSE 0 END) AS DEZ_FAT
FROM
	SD2010
WHERE 
	D2_FILIAL ='02'
	AND D2_TIPO ='N'
	AND D_E_L_E_T_ =''
	AND D2_EMISSAO BETWEEN '20190101' AND '20190731'
GROUP BY 
	D2_CLIENTE, D2_LOJA

---
@thiago.andrrade
